### ISSUE TITLE
建议在onDetachedFromWindow方法里调用下removeCountDown

### ISSUE THREAD

**Issue by typ0520** [WhiteDG/CountDownButton#1]
rt

**Comment by typ0520** [comment]
建议在增加一个api，有的需求是默认展示"获取验证码"，等计时跑完时显示重新获取
 
```
   public void setDefaultText(String defaultText) {
        this.mDefaultText = defaultText;
    }
```

**Comment by WhiteDG** [comment]
1. 根据你的建议已在onDetachedFromWindow方法里添加removeCountDown调用
2. 觉得defaultText变量名不太适合，改成cdFinishText了，新增了一个api setCDFinishText(String cdFinishText) 满足需求

**Comment by typ0520** [comment]
nice
